spring:
  flyway:
    enabled: true
  datasource:
    url: ${JDBC_URL}
#    hikari:
#      username: ${JDBC_USER}
#      password: ${JDBC_PASSWORD}
#      jdbc-url: ${JDBC_URL}
#      driver-class-name: com.mysql.cj.jdbc.Driver
