spring:
  flyway:
    enabled: true
  datasource:
    url: jdbc:mysql://address=(host=${DB_ADDRESS})(port=${DB_PORT})(user=${DB_USER})(password=${DB_PASSWORD})/${DB_DATABASE}
#    hikari:
#      username: ${JDBC_USER}
#      password: ${JDBC_PASSWORD}
#      jdbc-url: ${JDBC_URL}
#      driver-class-name: com.mysql.cj.jdbc.Driver
