name: "jib_comment"

on:
  issue_comment:

jobs:
  jib_comment:
    name: "jib_comment"
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request != null && github.event.comment.body == '.build' }}
    steps:
      - uses: actions/github-script@0.9.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### start :app:jib build....
            CI URL: ${process.env.GITHUB_SERVER_URL}/${process.env.GITHUB_REPOSITORY}/actions/runs/${process.env.GITHUB_RUN_ID}
            `
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      # - name: Checkout
      #   uses: actions/checkout@v2
      - uses: actions/github-script@v3
        id: get-pr
        with:
          script: |
            const request = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            }
            core.info(`Getting PR #${request.pull_number} from ${request.owner}/${request.repo}`)
            try {
              const result = await github.pulls.get(request)
              return result.data
            } catch (err) {
              core.setFailed(`Request failed with error ${err}`)
            }
      - uses: actions/checkout@v2
        with:
          repository: ${{ fromJSON(steps.get-pr.outputs.result).head.repo.full_name }}
          ref: ${{ fromJSON(steps.get-pr.outputs.result).head.ref }} # or .head.ref for branch name
          # ref: ${{ fromJSON(steps.get-pr.outputs.result).head.sha }} # or .head.ref for branch name

      # - name: "Checkout"
      #   uses: actions/checkout@v2
      #   with:
      #     ref: ${{ steps.get_branch.outputs.branch }}

      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: jib with Gradle (app)
        id: jib
        run: |
          (./gradlew :app:jib | tee output) 3>&1 1>&2 2>&3 | tee error
          echo "::set-output name=result::$(cat output)"
          echo "::set-output name=error::$(cat error)"
        env:
          DOCKER_REPOSITORY_BASE_URL: ${{ secrets.DOCKER_REPOSITORY_BASE_URL }}

      - name: Cleanup Gradle Cache
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties

      - uses: actions/github-script@0.9.0
        env:
          JIB: ${{ steps.jib.outputs.result }}
          JIB_ERROR: ${{ steps.jib.outputs.error }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### .build の結果を表示する。
            #### ./gradlew :app:jib 📖\`${{ steps.jib.outcome }}\`

            <details><summary>Show Jib Result</summary>

            \`\`\`txt
            ${process.env.JIB}
            \`\`\`

            </details>
            
            ${ process.env.JIB_ERROR &&
              `<details><summary>Error</summary>

              \`\`\`txt
              ${process.env.JIB_ERROR}
              \`\`\`

              </details>
            `}`;

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
      - name: Jib Status
        if: steps.jib.outcome == 'failure'
        run: exit 1
      - name: update tag version
        run: sed -i -e "s/^container_tag\(  *\)= \"\(..*\)\".*$/container_tag\1= \"`cat VERSION.txt`-`git rev-parse --short=7 HEAD`\"/g" terraform/env/dev/dev.auto.tfvars

      - name: GITHUB_SHA substring 0:7
        id: hash_substring
        run: |
          echo ${GITHUB_SHA:0:7}
      - name: git-auto commit
        env:
          INPUT_COMMIT_USER_NAME: GitHub Actions
          INPUT_COMMIT_USER_EMAIL: actions@github.com
        run: |
          commit_hash=${{ fromJSON(steps.get-pr.outputs.result).head.sha }}
          git add .
          git \
            -c user.name="$INPUT_COMMIT_USER_NAME" -c user.email="$INPUT_COMMIT_USER_EMAIL" \
            commit \
            -m "Update Tag Version(app) to ${commit_hash:0:7}" \
            --author="${{ github.event.comment.actor.login }}"
          git push --set-upstream origin ${{ fromJSON(steps.get-pr.outputs.result).head.ref }}
